export const modulesData = [
    { 
        id: 1, 
        title: "Onboarding", 
        submodules: [
            { title: "Introdução e Metodologia", desc: "Aulas e Materiais de estudo.", duration: "20 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=1&submodulo=1" },
            { title: "Ferramentas (Plataforma e Questões)", desc: "Aulas e Materiais de estudo.", duration: "20 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=1&submodulo=2" },
            { title: "Revisões do 1º Trimestre (Blocos 1-6)", desc: "Aulas e Materiais de estudo.", duration: "20 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=1&submodulo=3" },
            { title: "Revisões do 2º Trimestre (Blocos 7-12)", desc: "Aulas e Materiais de estudo.", duration: "20 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=1&submodulo=4" },
            { title: "Revisões do 3º Trimestre (Blocos 13-18)", desc: "Aulas e Materiais de estudo.", duration: "20 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=1&submodulo=5" },
            { title: "Revisões Finais (Blocos 19-24)", desc: "Aulas e Materiais de estudo.", duration: "20 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=1&submodulo=6" }
        ]
    },
    { 
        id: 2, 
        title: "Cirurgia Geral", 
        submodules: [
            { title: "Trauma: Introdução e Atendimento Inicial", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=2&submodulo=1" },
            { title: "Trauma: Vias Aéreas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=2&submodulo=2" },
            { title: "Trauma: Choque", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=2&submodulo=3" },
            { title: "Trauma: Ressuscitação Hemostática", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=2&submodulo=4" },
            { title: "Diagnósticos diferenciais das massas cervicais", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=2&submodulo=5" },
            { title: "Introdução ao Extensivo", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=2&submodulo=6" },
            { title: "Esvaziamentos cervicais + Anatomia", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=2&submodulo=7" }
        ]
    },
    { 
        id: 3, 
        title: "Clínica Médica", 
        submodules: [
            { title: "Síndrome Coronariana Aguda sem Supra de ST (SCASSST)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=1" },
            { title: "Síndrome Coronariana Aguda com Supra de ST (SCACSST)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=2" },
            { title: "Síndromes Aórticas Agudas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=3" },
            { title: "Pericardite e Miocardite", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=4" },
            { title: "Hipertensão Arterial Sistêmica (HAS)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=5" },
            { title: "Emergências Hipertensivas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=6" },
            { title: "Insuficiência Cardíaca - Manejo Ambulatorial", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=7" },
            { title: "Insuficiência Cardíaca - Descompensações Agudas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=8" },
            { title: "Taquiarritmias", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=9" },
            { title: "Bradiarritimias", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=10" },
            { title: "Síncope", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=11" },
            { title: "Febre Reumática e Endocardite", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=12" },
            { title: "Valvopatias", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=13" },
            { title: "BLS e ACLS", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=14" },
            { title: "Pneumonia Adquirida na Comunidade", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=15" },
            { title: "Derrame Pleural", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=16" },
            { title: "Asma", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=17" },
            { title: "Doença Pulmonar Obstrutiva Crônica (DPOC)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=18" },
            { title: "Tabagismo", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=19" },
            { title: "Espirometria", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=20" },
            { title: "Tromboembolismo Pulmonar (TEP)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=21" },
            { title: "Hipertensão pulmonar", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=22" },
            { title: "Distúrbios do Sono", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=23" },
            { title: "Doença Pulmonar Intersticial (DPI)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=24" },
            { title: "Nódulo Pulmonar", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=25" },
            { title: "Diabetes: Classificação, Fisiopatologia e Diagnóstico", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=26" },
            { title: "Meta Terapêutica, Manejo do pré-DM e Tratamento Não Farmacológico", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=27" },
            { title: "Antidiabéticos Orais e Subcutâneos - Parte 1", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=28" },
            { title: "Antidiabéticos Orais e Subcutâneos - Parte 2", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=29" },
            { title: "Insulinoterapia", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=30" },
            { title: "Complicações Crônicas do Diabetes Mellitus (DM)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=31" },
            { title: "Hiperglicemia Hospitalar", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=32" },
            { title: "Emergências Hiperglicêmicas (CAD e EHH)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=33" },
            { title: "Dislipidemia - Classificação e Diagnóstico", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=34" },
            { title: "Tratamento das Dislipidemias", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=35" },
            { title: "Síndrome Metabólica", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=36" },
            { title: "Obesidade: Introdução e Tratamento Não Farmacológico", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=37" },
            { title: "Obesidade: Tratamento Farmacológico e Cirúrgico", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=38" },
            { title: "Fisiologia da Tireoide", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=39" },
            { title: "Hipotireoidismo", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=40" },
            { title: "Hipertireoidismo", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=41" },
            { title: "Tireoidites & Síndrome do Eutireoidiano Doente", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=42" },
            { title: "Nódulos e Câncer de Tireoide", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=43" },
            { title: "Fisiologia e Anatomia da Adrenal", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=44" },
            { title: "Incidentaloma Adrenal", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=45" },
            { title: "Síndrome de Cushing", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=46" },
            { title: "Insuficiência Adrenal", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=47" },
            { title: "Hiperaldosteronismo Primário", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=48" },
            { title: "Feocromocitoma", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=49" },
            { title: "Prolactinomas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=50" },
            { title: "Dispepsia", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=51" },
            { title: "DRGE", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=52" },
            { title: "Úlcera péptica, H. pylori, Gastrite Atrófica e Dispepsia Funcional", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=53" },
            { title: "Disfagia, Esofagite Eosinofílica e Acalasias", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=54" },
            { title: "Diarreia Agudas e Colite Pseudomembranosa", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=55" },
            { title: "Diarreias Crônicas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=56" },
            { title: "Doença Inflamatória Intestinal (DII)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=57" },
            { title: "Avaliação de enzimas hepáticas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=58" },
            { title: "Doenças hepáticas: CBP, CEP, HAI e Doença de Wilson", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=59" },
            { title: "Doença hepática esteatótica Metabólica (DHEM)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=60" },
            { title: "Cirrose hepática: Conceitos Gerais", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=61" },
            { title: "Cirrose hepática: Ascite + PBE", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=62" },
            { title: "Cirrose hepática: Encefalopatia Hepática e Síndrome Hepatorrenal", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=63" },
            { title: "Cirrose hepática: Varizes esofágicas e Síndrome Hepatopulmonar", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=64" },
            { title: "Doenças oportunistas HIV", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=65" },
            { title: "HIV", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=66" },
            { title: "Antibióticos I", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=67" },
            { title: "Antibióticos II", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=68" },
            { title: "Sífilis e Uretrites Infecciosas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=69" },
            { title: "Neurossífilis", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=70" },
            { title: "Tuberculose Pulmonar", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=71" },
            { title: "Tratamento de Tuberculose e efeitos colaterais do RIPE", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=72" },
            { title: "Tuberculose Extra Pulmonar", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=73" },
            { title: "Doenças Negligenciadas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=74" },
            { title: "Acidentes com Animais Peçonhentos", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=75" },
            { title: "Vacinação - Situações Especiais", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=76" },
            { title: "Doenças Virais e Pandêmicas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=77" },
            { title: "Arboviroses", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=78" },
            { title: "Icterícias febris e Febre Maculosa", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=79" },
            { title: "Hepatites Virais", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=80" },
            { title: "Parasitoses Intestinais", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=81" },
            { title: "Acidente Vascular Cerebral Isquêmico (AVCi)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=82" },
            { title: "AVCi - Tratamento e complicações", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=83" },
            { title: "Acidente Vascular Cerebral Hemorrágico (AVCh) Intraparenquimatoso", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=84" },
            { title: "Hemorragia subaracnóidea (HSA)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=85" },
            { title: "Introdução às Cefaleias Primárias", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=86" },
            { title: "Enxaqueca (Migrânea)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=87" },
            { title: "Cefaleias Trigêmino-Autonômicas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=88" },
            { title: "Meningites e Encefalites", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=89" },
            { title: "Síndrome de Guillain-Barré (SGB)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=90" },
            { title: "Miastenia Gravis", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=91" },
            { title: "Epilepsia", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=92" },
            { title: "Doença de Parkinson", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=93" },
            { title: "Esclerose Múltipla (EM)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=94" },
            { title: "Neuromielite Óptica (NMO)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=95" },
            { title: "Gasometria Arterial I", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=96" },
            { title: "Gasometria Arterial II", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=97" },
            { title: "Distúrbios do Sódio", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=98" },
            { title: "Distúrbios do Potássio", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=99" },
            { title: "Distúrbios do Cálcio", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=100" },
            { title: "Distúrbios Hidroeletrolíticos - Outros (Magnésio e Fósforo)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=101" },
            { title: "Hipercalcemias", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=102" },
            { title: "Hipocalcemias", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=103" },
            { title: "Injúria Renal Aguda (IRA) - Parte 1", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=104" },
            { title: "Injúria Renal Aguda (IRA) - Parte 2", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=105" },
            { title: "Doença Renal Crônica I", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=106" },
            { title: "Doença Renal Crônica II", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=107" },
            { title: "Glomerulopatias I", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=108" },
            { title: "Glomerulopatias II", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=109" },
            { title: "Infecção do Trato Urinário (ITU)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=110" },
            { title: "Introdução às Artrites e Artrite Reumatoide (AR)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=111" },
            { title: "Espondiloartrites", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=112" },
            { title: "Artrites Microcristalinas (Gota e CPPD)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=113" },
            { title: "Osteoartrite", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=114" },
            { title: "Fibromialgia", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=115" },
            { title: "Vasculites de Grandes e Médios Vasos", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=116" },
            { title: "Vasculites de Pequenos Vasos", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=117" },
            { title: "Doença de Behçet", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=118" },
            { title: "Lúpus Eritematoso Sistêmico (LES)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=119" },
            { title: "Osteoporose", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=120" },
            { title: "Esclerose Sistêmica", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=121" },
            { title: "Doença de Sjögren", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=122" },
            { title: "Miopatias Autoimunes Sistêmicas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=123" },
            { title: "Avaliação Global do Hemograma", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=124" },
            { title: "Anemias Hipoproliferativas I", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=125" },
            { title: "Anemias Hipoproliferativas II", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=126" },
            { title: "Anemias Hemolíticas Adquiridas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=127" },
            { title: "Anemias Hemolíticas Hereditárias", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=128" },
            { title: "Púrpura Trombocitopênica Trombótica (PTT)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=129" },
            { title: "Fisiologia da Coagulação", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=130" },
            { title: "Distúrbios da Hemostasia", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=131" },
            { title: "Hemoterapia", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=132" },
            { title: "Leucemias", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=133" },
            { title: "Linfomas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=134" },
            { title: "Discrasias Plasmocitárias", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=135" },
            { title: "Síndromes Medulares", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=136" },
            { title: "Via aérea, intubação e Ventilação Não Invasiva (VNI)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=137" },
            { title: "Síndrome do desconforto respiratório agudo (SDRA)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=138" },
            { title: "Princípios de ventilação mecânica (VM)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=139" },
            { title: "Ventilação mecânica (VM) exercícios", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=140" },
            { title: "Pneumonia Associada à Ventilação Mecânica", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=141" },
            { title: "Intoxicações Exógenas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=142" },
            { title: "Choque - Abordagem Inicial", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=143" },
            { title: "Choque - Tipos de Choque", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=144" },
            { title: "Infecção de Corrente Sanguínea (ICS)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=145" },
            { title: "Analgesia e Sedação", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=146" },
            { title: "Drogas vasoativas (DVA)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=147" },
            { title: "Emergências psiquiátricas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=148" },
            { title: "Transtorno de Humor I", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=149" },
            { title: "Transtorno de Humor II - Antidepressivos", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=150" },
            { title: "Transtorno de Humor III - Mania e Transtorno Bipolar", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=151" },
            { title: "Transtorno de Ansiedade", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=152" },
            { title: "Transtornos Relacionados a Substâncias - Álcool", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=153" },
            { title: "Transtorno Psicótico", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=154" },
            { title: "Transtorno alimentares e somatoformes", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=155" },
            { title: "Transtorno de personalidade", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=156" },
            { title: "Introdução à Geriatria", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=157" },
            { title: "Avaliação Geriátrica Ampla", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=158" },
            { title: "Iatrogenia no Idoso", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=159" },
            { title: "Instabilidade Postural, Quedas e Imobilidade", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=160" },
            { title: "Vacinação do Idoso", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=161" },
            { title: "Depressão no Idoso", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=162" },
            { title: "Insuficiência Cognitiva - Demências", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=163" },
            { title: "Insuficiência Cognitiva - Delirium no Idoso", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=164" },
            { title: "Fragilidade", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=165" },
            { title: "Incontinência Urinária no Idoso", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=166" },
            { title: "Hanseníase", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=167" },
            { title: "Lesões Elementares", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=168" },
            { title: "Dermatoses Bolhosas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=169" },
            { title: "Psoríase", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=170" },
            { title: "Otologia I", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=171" },
            { title: "Otologia II", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=172" },
            { title: "Rinologia", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=173" },
            { title: "Bucofaringolaringologia I", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=174" },
            { title: "Bucofaringolaringologia II", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=175" },
            { title: "Oftalmologia para o generalista - parte I", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=176" },
            { title: "Oftalmologia para o generalista - parte II", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=177" },
            { title: "Rastreamentos - Clínica Médica", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=178" },
            { title: "Oncologia - Cuidados paliativos", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=179" },
            { title: "Emergências Oncológicas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=180" },
            { title: "Alergia 1 - Rinite e Angioedema", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=181" },
            { title: "Alergia 2 - Reações de hipersensibilidade", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=3&submodulo=182" }
        ]
    },
    { 
        id: 4, 
        title: "Ginecologia e Obstetrícia", 
        submodules: [
            { title: "Assistência ao Pré-Natal", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=1" },
            { title: "Síndromes Hipertensivas na Gestação", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=2" },
            { title: "Sangramentos da 1ª Metade (Abortamento e Ectópica)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=3" },
            { title: "Sangramentos da 2ª Metade (Placenta Prévia e DPP)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=4" },
            { title: "Mecanismo e Assistência ao Parto", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=5" },
            { title: "Hemorragia Pós-Parto", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=6" },
            { title: "Infecções Genitais (Corrimentos, Úlceras e DIP)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=7" },
            { title: "Anticoncepção (Métodos e Critérios de Elegibilidade)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=8" },
            { title: "Rastreamento de Câncer de Colo (Pap e Condutas)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=9" },
            { title: "Câncer de Mama (Rastreamento e BI-RADS)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=10" },
            { title: "Diabetes na Gestação", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=11" },
            { title: "Rotura Prematura de Membranas (RPMO)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=12" },
            { title: "Trabalho de Parto Prematuro (TPP)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=13" },
            { title: "Fisiologia Menstrual e Amenorreias", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=14" },
            { title: "Síndrome dos Ovários Policísticos (SOP)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=15" },
            { title: "Sangramento Uterino Anormal (SUA) e Miomatose", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=16" },
            { title: "Incontinência Urinária e Prolapsos", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=17" },
            { title: "Nódulos Benignos da Mama", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=18" },
            { title: "Doença Hemolítica Perinatal", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=19" },
            { title: "Modificações do Organismo Materno", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=20" },
            { title: "Avaliação da Vitalidade Fetal e Sofrimento", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=21" },
            { title: "Restrição de Crescimento Intrauterino (RCIU)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=22" },
            { title: "Climatério e Terapia Hormonal (TRH)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=23" },
            { title: "Endometriose", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=24" },
            { title: "Infertilidade Conjugal", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=25" },
            { title: "Infecções e Gravidez (Não Ginecológicas)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=26" },
            { title: "Gemelaridade", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=27" },
            { title: "Câncer de Colo de Útero (Invasor)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=28" },
            { title: "Câncer de Ovário e Tumores Anexiais", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=29" },
            { title: "Câncer de Endométrio e Hiperplasia", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=30" },
            { title: "Anatomia e Embriologia", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=31" },
            { title: "Malformações Mullerianas e Congênitas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=32" },
            { title: "Estática Fetal", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=33" },
            { title: "Doença Trofoblástica Gestacional (DTG)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=34" },
            { title: "Puberdade e Distúrbios do Desenvolvimento Sexual", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=35" },
            { title: "Medicina Fetal (Aneuploidias e Procedimentos)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=36" },
            { title: "Violência Sexual e Aborto Legal", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=37" },
            { title: "Trombofilias", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=38" },
            { title: "Ultrassonografia em Obstetrícia", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=39" },
            { title: "Cirurgia Ginecológica e Urgências", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=4&submodulo=40" }
        ]
    },
    { 
        id: 5, 
        title: "Pediatria", 
        submodules: [
            { title: "Aleitamento Materno", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=1" },
            { title: "Alimentação Infantil", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=2" },
            { title: "Crescimento e Baixa Estatura", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=3" },
            { title: "Desenvolvimento Infantil", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=4" },
            { title: "Vacinação 1 e 2", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=5" },
            { title: "Pneumonias", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=6" },
            { title: "Bronquiolite e Coqueluche", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=7" },
            { title: "Asma", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=8" },
            { title: "Infecções de Vias Aéreas Superiores (IVAS)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=9" },
            { title: "Diarreia Aguda", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=10" },
            { title: "Reanimação Neonatal", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=11" },
            { title: "Icterícia e Colestase Neonatal", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=12" },
            { title: "Febre sem Sinais Localizatórios (FSSL)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=13" },
            { title: "Infecção de Trato Urinário (ITU)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=14" },
            { title: "Doenças Exantemáticas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=15" },
            { title: "Síndromes Nefrítica e Nefrótica", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=16" },
            { title: "Anemias Carenciais (Ferropriva)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=17" },
            { title: "Desconforto Respiratório Neonatal", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=18" },
            { title: "Infecções Congênitas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=19" },
            { title: "Choque e Sepse Pediátrica", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=20" },
            { title: "Distúrbio Hidroeletrolítico e Ácido-Básico", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=21" },
            { title: "Cetoacidose Diabética (CAD)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=22" },
            { title: "Parasitoses Intestinais", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=23" },
            { title: "Puberdade", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=24" },
            { title: "Obesidade e Síndrome Metabólica", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=25" },
            { title: "Alergia Alimentar, Refluxo e Constipação", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=26" },
            { title: "Anemia Falciforme", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=27" },
            { title: "Meningite e Encefalite", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=28" },
            { title: "Convulsões e Epilepsia", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=29" },
            { title: "Cardiopatias Congênitas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=30" },
            { title: "Sepse Neonatal", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=31" },
            { title: "Dermatite Atópica e Lesões do RN", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=32" },
            { title: "Arboviroses", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=33" },
            { title: "Tuberculose", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=34" },
            { title: "Suporte Avançado (PALS)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=35" },
            { title: "Reumatologia Pediátrica", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=36" },
            { title: "Oncologia Pediátrica", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=37" },
            { title: "Imunodeficiências", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=38" },
            { title: "Fibrose Cística", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=39" },
            { title: "Intoxicações e Acidentes", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=40" },
            { title: "Ingestão de Corpo Estranho", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=41" },
            { title: "Nutrologia e Vitaminas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=42" },
            { title: "Triagens e Metabólicos Neonatais", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=43" },
            { title: "Ortopedia Pediátrica", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=44" },
            { title: "Oftalmo e Otorrino Pediátricos", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=45" },
            { title: "Genética e Malformações", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=46" },
            { title: "Psiquiatria e Sono", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=47" },
            { title: "Ética e Cuidados Paliativos", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=48" },
            { title: "Ventilação Mecânica e Sedação", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=5&submodulo=49" }
        ]
    },
    { 
        id: 6, 
        title: "Preventiva", 
        submodules: [
            { title: "Lei Orgânica de Saúde: 8080/90", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=1" },
            { title: "Lei Orgânica de Saúde: 8142/90", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=2" },
            { title: "Princípios do SUS", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=3" },
            { title: "Testes Diagnósticos (Características e Cálculos)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=4" },
            { title: "Classificação dos Estudos Epidemiológicos", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=5" },
            { title: "Estudos Longitudinais e Transversais", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=6" },
            { title: "Atenção Primária à Saúde (APS)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=7" },
            { title: "Estratégia Saúde da Família (ESF)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=8" },
            { title: "Princípios da Medicina de Família e Comunidade", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=9" },
            { title: "Ferramentas da APS/ESF (Genograma, Ecomapa)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=10" },
            { title: "Método Clínico Centrado na Pessoa (MCCP)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=11" },
            { title: "Medicina Legal (Declaração de Óbito e Atestados)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=12" },
            { title: "Ética Médica", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=13" },
            { title: "Níveis de Prevenção (Primária a Quaternária)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=14" },
            { title: "Indicadores de Saúde", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=15" },
            { title: "Vigilância em Saúde", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=16" },
            { title: "Medidas de Associação", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=17" },
            { title: "Financiamento do SUS", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=18" },
            { title: "Ensaio Clínico", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=19" },
            { title: "Acidente de Trabalho", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=20" },
            { title: "Doenças Ocupacionais (Pneumoconioses e LER/DORT)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=21" },
            { title: "Intoxicações Ocupacionais e Burnout", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=22" },
            { title: "História da Saúde no Brasil", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=23" },
            { title: "Decreto 7508/11", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=24" },
            { title: "Saúde Suplementar", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=25" },
            { title: "Medicina Baseada em Evidências (MBE)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=26" },
            { title: "Habilidades de Comunicação", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=27" },
            { title: "Políticas Públicas de Saúde (Populações Especiais)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=28" },
            { title: "Saúde Mental e RAPS", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=29" },
            { title: "Determinação Social do Processo Saúde-Doença", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=30" },
            { title: "Rastreamentos", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=31" },
            { title: "Abordagem Familiar e Comunitária", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=32" },
            { title: "ReSOAP e Registro Clínico", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=33" },
            { title: "\"Foca na APS\" (Revisão Clínica em Preventiva)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=34" },
            { title: "NOBs e NOAS", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=35" },
            { title: "Pacto pela Saúde", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=36" },
            { title: "Concepções sobre Saúde e Doença", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=37" },
            { title: "Planejamento em Saúde", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=38" },
            { title: "Ética em Pesquisa Clínica", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=39" },
            { title: "Saúde Planetária", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=40" },
            { title: "Redes de Atenção à Saúde (RAS)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=41" },
            { title: "Avaliação e Tecnologia em Saúde", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=6&submodulo=42" }
        ]
    },
    { 
        id: 7, 
        title: "Cirurgia Completa / Neuro & Psiquiatria", 
        submodules: [
            { title: "Trauma: Revisão ABCDE", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=1" },
            { title: "Trauma de Tórax I", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=2" },
            { title: "Trauma de Tórax II", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=3" },
            { title: "Medidas Auxiliares e FAST", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=4" },
            { title: "Trauma em Populações Especiais", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=5" },
            { title: "Trauma Abdominal Penetrante", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=6" },
            { title: "Trauma Abdominal Contuso", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=7" },
            { title: "Trauma Abdominal Específico (Parte 1)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=8" },
            { title: "Trauma Abdominal Específico (Parte 2)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=9" },
            { title: "Trauma de Pelve", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=10" },
            { title: "Trauma Cervical", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=11" },
            { title: "Trauma Cranioencefálico (TCE)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=12" },
            { title: "Trauma Raquimedular (TRM)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=13" },
            { title: "Trauma Musculoesquelético", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=14" },
            { title: "Anatomia da Parede Abdominal", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=15" },
            { title: "Hérnia Inguinal", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=16" },
            { title: "Hernioplastia Inguinal", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=17" },
            { title: "Hérnia Femoral e Umbilical", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=18" },
            { title: "Hérnias Incisionais e Outras", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=19" },
            { title: "Abdome Agudo: Introdução", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=20" },
            { title: "Apendicite Aguda", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=21" },
            { title: "Colelitíase e Colecistite", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=22" },
            { title: "Coledocolitíase e Colangite", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=23" },
            { title: "Pancreatite Aguda", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=24" },
            { title: "Diverticulite Aguda", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=25" },
            { title: "Abdome Agudo Obstrutivo", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=26" },
            { title: "Abdome Agudo Perfurativo", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=27" },
            { title: "Abdome Agudo Vascular", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=28" },
            { title: "Abdome Agudo Hemorrágico", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=29" },
            { title: "Esôfago: Introdução e Disfagia", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=30" },
            { title: "Câncer de Esôfago", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=31" },
            { title: "Acalasia", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=32" },
            { title: "DRGE, Barrett e Hérnias de Hiato", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=33" },
            { title: "Estômago: Anatomia e Fisiologia", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=34" },
            { title: "Adenocarcinoma Gástrico e Linfomas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=35" },
            { title: "GIST e Tumores Neuroendócrinos Gástricos", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=36" },
            { title: "Complicações pós gastrectomias", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=37" },
            { title: "Obesidade e Cirurgia Bariátrica", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=38" },
            { title: "Complicações Pós-Bariátrica e Reganho", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=39" },
            { title: "Fígado: Anatomia e Lesões Benignas (Adenoma, HNF, Hemangioma)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=40" },
            { title: "Carcinoma Hepatocelular", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=41" },
            { title: "Metástases Hepáticas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=42" },
            { title: "Abscesso e Cistos Hepáticos", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=43" },
            { title: "Patologias da Vesícula (Pólipos, Cistos, Câncer)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=44" },
            { title: "Lesão Iatrogênica da Via Biliar", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=45" },
            { title: "Adenocarcinoma de Pâncreas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=46" },
            { title: "Pancreatite Crônica", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=47" },
            { title: "Tumores Periampulares e Císticos do Pâncreas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=48" },
            { title: "Câncer Colorretal e Síndromes Associadas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=49" },
            { title: "Doenças Orificiais", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=50" },
            { title: "CEC Canal Anal e Pilonidal", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=51" },
            { title: "Doença Inflamatória Intestinal (DII)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=52" },
            { title: "Tumores do Intestino Delgado e SII", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=53" },
            { title: "Distúrbios do Assoalho Pélvico", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=54" },
            { title: "Hemorragia Digestiva Alta (Varicosa e Não Varicosa)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=55" },
            { title: "Hemorragia Digestiva Baixa e Média", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=56" },
            { title: "Corpo Estranho e Preparo de Cólon", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=57" },
            { title: "Pólipos Colorretais e CA Precoce", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=58" },
            { title: "Litíase Urinária: Diagnóstico e Tratamento", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=59" },
            { title: "Câncer de Próstata, Rim e Bexiga", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=60" },
            { title: "Câncer de Testículo, Pênis e Adrenal", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=61" },
            { title: "Hiperplasia Prostática Benigna (HPB)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=62" },
            { title: "Urgências Urológicas (Escroto Agudo, Priapismo, Fratura)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=63" },
            { title: "Trauma Urológico (Rim, Ureter, Bexiga, Uretra)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=64" },
            { title: "Incontinência, Bexiga Neurogênica e Disfunções", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=65" },
            { title: "Andrologia (Medicina Sexual, DSTs, Infertilidade)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=66" },
            { title: "Aneurisma de Aorta", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=67" },
            { title: "Síndromes Aórticas Agudas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=68" },
            { title: "Doença Arterial Obstrutiva (OAA e OAC)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=69" },
            { title: "Trombose Venosa Profunda (TVP) e Insuficiência Venosa", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=70" },
            { title: "Estenose Carotídea", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=71" },
            { title: "Trauma Vascular", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=72" },
            { title: "Pé Diabético e Vasculites", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=73" },
            { title: "Tireoide: Anatomia, Fisiologia e Tireoidites", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=74" },
            { title: "Nódulos e Câncer de Tireoide", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=75" },
            { title: "Tireoidectomia e Esvaziamento", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=76" },
            { title: "Paratireoide e Hiperparatireoidismo", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=77" },
            { title: "Anomalias Congênitas e Câncer de Pele (Cabeça e Pescoço)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=78" },
            { title: "Derrame Pleural e Pneumotórax", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=79" },
            { title: "Câncer de Pulmão", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=80" },
            { title: "Mediastino e Doenças Traqueais", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=81" },
            { title: "Cirurgia Cardíaca: Coronária, Valvas e Aorta", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=82" },
            { title: "Pós-Operatório e Transplante Cardíaco", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=83" },
            { title: "Queimados: Atendimento Inicial e Tratamento", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=84" },
            { title: "Cicatrização, Enxertos e Retalhos", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=85" },
            { title: "Cirurgia da Mama e Contorno Corporal", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=86" },
            { title: "Trauma de Face e Paralisia Facial", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=87" },
            { title: "Defeitos da Parede e Região Inguinal", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=88" },
            { title: "Vômitos no Lactente e CIPE", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=89" },
            { title: "Tumores e Malformações (Esôfago, Via Biliar, Cólon)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=90" },
            { title: "Avaliação Pré-Operatória e Risco", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=91" },
            { title: "REMIT e Complicações Pós-Operatórias", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=92" },
            { title: "Técnicas Anestésicas e Monitorização", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=93" },
            { title: "Nutrição Perioperatória", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=94" },
            { title: "Videolaparoscopia e Eletrocirurgia", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=95" },
            { title: "Ortopedia Geral e Traumatologia", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=96" },
            { title: "Neurocirurgia: Emergências e Geral", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=97" },
            { title: "Oncocirurgia Geral (Melanoma e Sarcoma)", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=98" },
            { title: "Doenças Cirúrgicas do Baço", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=7&submodulo=99" }
        ]
    },
    { 
        id: 8, 
        title: "Neuropediatria", 
        submodules: [
            { title: "Alterações no Neurodesenvolvimento", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=8&submodulo=1" },
            { title: "Paralisia Cerebral e Outros Distúrbios do Movimento", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=8&submodulo=2" },
            { title: "Síndromes Neurocutâneas na Infância", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=8&submodulo=3" },
            { title: "Neoplasias de Sistema Nervoso Central", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=8&submodulo=4" },
            { title: "Alterações na Forma e Volume do Crânio", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=8&submodulo=5" },
            { title: "Ataxias na Infância", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=8&submodulo=6" },
            { title: "Doenças Desmielinizantes e Encefalite Autoimune", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=8&submodulo=7" },
            { title: "Neurologia Fetal e Neonatal", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=8&submodulo=8" },
            { title: "Neurovascular Infantil", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=8&submodulo=9" },
            { title: "Bases da Neurociência", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=8&submodulo=10" },
            { title: "Erros Inatos do Metabolismo e Doenças Neurodegenerativas", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=8&submodulo=11" },
            { title: "Doenças Sistêmicas com Acometimento do SNC", desc: "Aulas e Materiais de estudo.", duration: "30 min", link: "https://medicinajvs.github.io/medcofr1/?modulo=8&submodulo=12" }
        ]
    }
];